### PR TITLE
Removed the GATEWAY_ID from the ipsec.secrets file as it did not work

### PR DESCRIPTION
**Pull request by mmattes**
with strongswan for me. 

The generated ipsec.secrets looked like this but strongswan could not connect like this.
%any @192.168.90.1 : PSK "MYSECRET"

the ipsec.secrets file like this worked for me: 
%any : PSK "MYSECRET"

May this helps...

### CODE REVIEW

**Comment by dkosovic** [comment]
I've just got to do a bit of research before accepting this pull request to make sure there isn't some obscure reason why the second argument before the colon was in there in the first place, but pretty sure your solution will be fine.

If there is some obscure reason, I'll fix the code so that ipsec.secrets becomes :
%any 192.168.90.1 : PSK "MYSECRET"

I have some exisiting code elsewhere to remove the @ symbol from an ID if it is an IP address

**Comment by mmattes** [comment]
Im sorry but I cant confirm that the following will work. 
%any 192.168.90.1 : PSK "MYSECRET"

only the combinations worked for me
%any : PSK "MYSECRET"
%any %any : PSK "MYSECRET"

I have also tried this which comes from the bottom here from [here](https://wiki.strongswan.org/projects/strongswan/wiki/IdentityParsing) but it did not work
%any ipv4:#0a000001 : PSK "MYSECRET"

**Comment by mmattes** [comment]
i hope these changes make more sense

**Comment by dkosovic** [comment]
Sorry for my tardiness, been away from home. I was happy with your original pull request as that's what I normally do when I manually setup a ipsec.secrets file for both strongSwan and Libreswan, I was probably just being a bit overcautious.

I'll be working on the code over the weekend to finish off a few things in preparation for the next release. Will most likely merge the pull request tomorrow when I'm less tired and want to do a better check.

**Pull request merged**
